### ISSUE TITLE
Can we avoid loading ActionMailer?

### ISSUE THREAD

**Issue by fgrehm** [basecamp/audits1984#62]
Hey folks! :wave: 

I'm trying out the gem in development but am having trouble with `action_mailer`:

```
16:07 $ rails console

Type 'jobs_help' to see how to connect to the available job servers to manage jobs

/.../ruby/3.3.5/lib/ruby/gems/3.3.0/gems/audits1984-0.1.7/app/mailers/audits1984/application_mailer.rb:2:in `<module:Audits1984>': uninitialized constant Audits1984::ActionMailer (NameError)

  class ApplicationMailer < ActionMailer::Base
                            ^^^^^^^^^^^^
Did you mean?  ActionView
        from /.../ruby/3.3.5/lib/ruby/gems/3.3.0/gems/audits1984-0.1.7/app/mailers/audits1984/application_mailer.rb:1:in `<main>'
        from /.../ruby/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
        from /.../ruby/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
```

We cherry pick the Rails engines used by our app and we don't use `action_mailer`. I tried to uncomment the `require "action_mailer/railtie"` on our `application.rb` but ended up hitting other problems.

Any thoughts around this?

PS: I ended up moving on to other things _for now_ :sob: Will come back to this another time :pray:  :crossed_fingers:

**Comment by flavorjones** [comment]
@fgrehm This entire class and file can probably be removed from engine, it looks like the default mountable engine template file. Happy to accept a PR!

**Comment by flavorjones** [comment]
Ah - see https://github.com/basecamp/audits1984/pull/53
